# Generated by Django 5.1.4 on 2024-12-19 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='总分')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('submitted', '已提交'), ('graded', '已批改')], default='in_progress', max_length=20, verbose_name='状态')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='teacher.exampaper', verbose_name='试卷')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生考试记录',
                'verbose_name_plural': '学生考试记录',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'exam_paper')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='答案内容')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='得分')),
                ('auto_graded', models.BooleanField(default=False, verbose_name='是否自动评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='teacher.question', verbose_name='试题')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='teacher.studentexam', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '学生答案',
                'verbose_name_plural': '学生答案',
                'ordering': ['question_id'],
                'unique_together': {('student_exam', 'question')},
            },
        ),
    ]
