# Generated by Django 5.1.4 on 2024-12-22 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_remove_exampaper_is_template_alter_exampaper_subject_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(verbose_name='总人数')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='平均分')),
                ('highest_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最高分')),
                ('lowest_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最低分')),
                ('passing_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='及格率')),
                ('score_distribution', models.JSONField(help_text='格式：{"0-60": 10, "60-70": 20, ...}', verbose_name='分数分布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.class', verbose_name='班级')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_analyses', to='teacher.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '成绩分析',
                'verbose_name_plural': '成绩分析',
                'ordering': ['-created_at'],
            },
        ),
    ]
